Train dataset size: 744
Validation dataset size: 65
Sample shape: torch.Size([32, 384, 384, 20]), dtype: torch.float32. maximum value: 0.9960784912109375, minimum value: 0.0
Sample shape: torch.Size([32, 384, 384, 20]), dtype: torch.float32. maximum value: 0.9960784912109375, minimum value: 0.0
Epoch 1/3 [Train]:   1%|                     | 4/744 [00:24<1:16:54,  6.24s/it, Loss=0.1502]
Traceback (most recent call last):
  File "/home/vatsal/NWM/fno_sevir/fno_vae_train.py", line 130, in <module>
    for batch_idx, data in pbar:
                           ^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/home/vatsal/NWM/fno_sevir/fno_dataset.py", line 760, in __next__
    ret_dict = self._sequent_sample()
  File "/home/vatsal/NWM/fno_sevir/fno_dataset.py", line 992, in _sequent_sample
    ret_dict[imgt] = np.concatenate((ret_dict[imgt], sampled_seq),
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                    axis=0)
                                    ^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback <function _start_and_connect_service.<locals>.teardown_atexit at 0x7fb9506bdf80>:
Traceback (most recent call last):
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/vatsal/miniconda3/lib/python3.13/threading.py", line 1092, in join
    self._handle.join(timeout)
KeyboardInterrupt:
